### ISSUE TITLE
Telegram Call is not working

### ISSUE THREAD

**Issue by x0r2d2** [shadowsocksrr/shadowsocksr-android#74]
Config: none + auth_chain_a + tls1.2_ticket_auth

With this config Telegram call is not working on latest stable build but with the same config Telegram Call is working with this build https://github.com/shadowsocksr-backup/shadowsocksr-android/releases/tag/3.4.0.8

**Comment by Akkariiin** [comment]
it's need no have different.
need time to find reason.

and if you have more info , please reply.

**Comment by x0r2d2** [comment]
@Akkariiin 
I will test it again and reply.

**Comment by mahyari** [comment]
I have a same problem with it. Telegram Call and Whatsapp Call are not working correct behind the proxy.

My config:
-  "-m", "aes-128-cfb", "-O", "auth_aes128_md5", "-o", "tls1.2_ticket_auth"

**Comment by x0r2d2** [comment]
@mahyari Did you turn on UDP forwarding? Android or iOS?

**Comment by mahyari** [comment]
> @mahyari Did you turn on UDP forwarding? Android or iOS?

Yes, But nothing changed. I used Android client on multiple devices but result is the same.
Whatsapp Call is not blocked in my area and work fine without proxy, but when I turn on proxy it stay in connecting state. 

I use docker in server with following config:

```
version: "3.7"
services:
    ssrr:
        image: oobs/ssrr:latest
        networks:
            - inet
        ports:
            - "9090:9090/tcp"
            - "9090:9090/udp"
        deploy:
            restart_policy:
                condition: on-failure
        entrypoint: ["python", "server.py", "-p", "9090", "-k", "password", "-m", "aes-128-cfb", "-O", "auth_aes128_md5", "-o", "tls1.2_ticket_auth","-vv","--fast-open"]

networks:
    inet:
```

No firewall is active on server. I'm not sure the problem raise from server or client, and have no way to test it.
